"""user_model_fields

Revision ID: fa5b7abd4f78
Revises: a9c12b1d7888
Create Date: 2026-06-23 00:16:32.689306

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa5b7abd4f78"
down_revision: str | Sequence[str] | None = "a9c12b1d7888"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("refresh_tokens", sa.Column("revoked", sa.Boolean(), nullable=False))
    op.add_column(
        "refresh_tokens", sa.Column("user_agent", sa.String(length=512), nullable=True)
    )
    op.add_column(
        "refresh_tokens", sa.Column("ip_address", sa.String(length=45), nullable=True)
    )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.alter_column(
        "refresh_tokens",
        "token_hash",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("refresh_tokens_token_hash_key"), "refresh_tokens", type_="unique"
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.add_column("users", sa.Column("is_superadmin", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("auth_provider", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("is_email_confirmed", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("pending_email", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "last_confirmation_sent_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column("users", sa.Column("token_version", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_column("users", "token_version")
    op.drop_column("users", "last_confirmation_sent_at")
    op.drop_column("users", "pending_email")
    op.drop_column("users", "is_email_confirmed")
    op.drop_column("users", "google_id")
    op.drop_column("users", "auth_provider")
    op.drop_column("users", "is_superadmin")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.create_unique_constraint(
        op.f("refresh_tokens_token_hash_key"),
        "refresh_tokens",
        ["token_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "refresh_tokens",
        "token_hash",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.drop_column("refresh_tokens", "updated_at")
    op.drop_column("refresh_tokens", "ip_address")
    op.drop_column("refresh_tokens", "user_agent")
    op.drop_column("refresh_tokens", "revoked")
    # ### end Alembic commands ###
